### ISSUE TITLE
似乎多显卡支持有点问题

### ISSUE THREAD

**Issue by XL8Z** [BlinkDL/RWKV-CUDA#6]
在用RWKV_Role_Playing项目
当使用`--strategy='cuda:1 fp32 *26 -> cuda:0 fp32'  --jit_on=1 --cuda_on=1 `时
会在生成时崩溃报错

```
Traceback (most recent call last):
  File "/srv/RWKV/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/srv/RWKV/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/srv/RWKV/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/srv/RWKV/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/srv/RWKV/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/srv/RWKV/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/srv/RWKV/RWKV_Role_Playing/modules/ui.py", line 75, in __load_char
    chatbot = self.chat_model.load_init_prompt(char['user'], char['bot'], char['action_start'],
  File "/srv/RWKV/RWKV_Role_Playing/modules/chat.py", line 48, in load_init_prompt
    out, model_tokens, model_state = self.model_utils.run_rnn(model_tokens, model_state, self.model_utils.fix_tokens(self.model_utils.pipeline.encode(init_prompt)))
  File "/srv/RWKV/RWKV_Role_Playing/modules/model_utils.py", line 32, in run_rnn
    out, model_state = self.model.forward(tokens[:self.CHUNK_LEN], model_state)
  File "/srv/RWKV/RWKV_Role_Playing/rwkv/model.py", line 607, in forward
    x, state[i*5+0], state[i*5+1], state[i*5+2], state[i*5+3] = ATT(
torch.jit.Error: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/srv/RWKV/RWKV_Role_Playing/rwkv/model.py", line 39, in cuda_att_seq
    def cuda_wkv(T: int, C: int, w, u, k, v, aa, bb, pp):
        assert 1 * C % min(C, 32) == 0
        assert k.dtype == torch.float16
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        w = w.contiguous()
        u = u.contiguous()
RuntimeError: AssertionError:

^CKeyboard interruption in main thread... closing server.

```
去掉`--cuda_on=1`关闭RWKV-CUDA后正常
不去掉`--cuda_on=1`，但是`--strategy='cuda:1 fp16`也正常
当使用`--strategy='cuda:1 fp32 *26 -> cpu fp32'`时再次故障

**目前看来排除法复现分析应该是
RWKV-CUDA启用时不能使用任何多硬件联合计算功能**

**Comment by BlinkDL** [comment]
可以用 https://github.com/josStorer/RWKV-Runner
